//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prueba.WSLoad {
    using System;
    using System.Data;
    using System.Windows.Forms;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSLoad.DBSoap")]
    public interface DBSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoadData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Data.DataTable LoadData(string query, string[] parameter, object[] values, string table);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ADDAfiliado", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        void ADDAfiliado(string DPI, string NombreCom, string FechaNac, int Telefono, float MontoCob, string TipoPoliza);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DELAfiliado", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        void DELAfiliado(string DPI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Actualiza_Afiliado", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        void Actualiza_Afiliado(string DPI, string NombreCom, string FechaNac, int Telefono, string InicioCob, string FinCobertura, float MontoCob, string TipoPoliza);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddProveedor", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        void AddProveedor(string NIT, string Nombre, string Dirreccion, int Telefono, string Pais, string Ciudad, string Correo, string Encargado, int Estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DelProveddor", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        void DelProveddor(string NIT);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModProveedor", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        void ModProveedor(string NIT, string Nombre, string Dirreccion, int Telefono, string Pais, string Ciudad, string Correo, string Encargado, int Estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddTran", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        void AddTran(string DPI, float monto, System.DateTime FinCobertura);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAfililiado", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        string GetAfililiado(string NIT, string DPI, string FechNac, string FechCob);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DBSoapChannel : Prueba.WSLoad.DBSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DBSoapClient : System.ServiceModel.ClientBase<Prueba.WSLoad.DBSoap>, Prueba.WSLoad.DBSoap {
        
        public DBSoapClient() {
        }
        
        public DBSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DBSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DBSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DBSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Data.DataTable LoadData(string query, string[] parameter, object[] values, string table) {
            return base.Channel.LoadData(query, parameter, values, table);
        }
        
        public void ADDAfiliado(string DPI, string NombreCom, string FechaNac, int Telefono, float MontoCob, string TipoPoliza) {
            base.Channel.ADDAfiliado(DPI, NombreCom, FechaNac, Telefono, MontoCob, TipoPoliza);
        }
        
        public void DELAfiliado(string DPI) {
            base.Channel.DELAfiliado(DPI);
        }
        
        public void Actualiza_Afiliado(string DPI, string NombreCom, string FechaNac, int Telefono, string InicioCob, string FinCobertura, float MontoCob, string TipoPoliza) {
            base.Channel.Actualiza_Afiliado(DPI, NombreCom, FechaNac, Telefono, InicioCob, FinCobertura, MontoCob, TipoPoliza);
        }
        
        public void AddProveedor(string NIT, string Nombre, string Dirreccion, int Telefono, string Pais, string Ciudad, string Correo, string Encargado, int Estado) {
            base.Channel.AddProveedor(NIT, Nombre, Dirreccion, Telefono, Pais, Ciudad, Correo, Encargado, Estado);
        }
        
        public void DelProveddor(string NIT) {
            base.Channel.DelProveddor(NIT);
        }
        
        public void ModProveedor(string NIT, string Nombre, string Dirreccion, int Telefono, string Pais, string Ciudad, string Correo, string Encargado, int Estado) {
            base.Channel.ModProveedor(NIT, Nombre, Dirreccion, Telefono, Pais, Ciudad, Correo, Encargado, Estado);
        }
        
        public void AddTran(string DPI, float monto, System.DateTime FinCobertura) {
            base.Channel.AddTran(DPI, monto, FinCobertura);
        }
        
        public string GetAfililiado(string NIT, string DPI, string FechNac, string FechCob) {
            return base.Channel.GetAfililiado(NIT, DPI, FechNac, FechCob);
        }

        internal void AddTran(TextBox txtNit, TextBox txtmontoP, Label lbFinCobertura)
        {
            throw new NotImplementedException();
        }
    }
}
